### ISSUE TITLE
locator中updateURL函数为啥还要比较一次getLocation() !== url

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/er#163]
RT。注释中说是“Opera下，相同的hash重复写入会在历史堆栈中重复记录，需要再行与当前的hash比较”，可是我的理解是var changed = currentLocation !== url; 这个应该已经包含了这种比较了吧？是有啥例外情况吗？

**Comment by otakustay** [comment]
看上去下面的判断是多余的，而且这个在比较老的Opera下才会发生

不过现在不打算去掉这个判断了
